### ISSUE TITLE
FileNotFoundError: No file 'Assets\Player/Idle Sword/Idle Sword 01.png' found in working directory

### ISSUE THREAD

**Issue by SuperArcherG** [Pandora241202/Adventure#2]
`FileNotFoundError: No file 'Assets\Player/Idle Sword/Idle Sword 01.png' found in working directory '/home/archer/Adventure'.`

You can fix this by updating `self.sprites.append(pygame.image.load(os.path.join('Assets\Player', 'Idle Sword/Idle Sword 01.png')))` to `self.sprites.append(pygame.image.load(os.path.join('Assets/Player', 'Idle Sword/Idle Sword 01.png')))`

The backslash is not traditionally used on linux systems and may/will cause issues
Logs are as follows:

```
archer@penguin:~/Adventure$ python3 main.py
pygame 2.5.2 (SDL 2.28.2, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/archer/Adventure/main.py", line 169, in <module>
    game.run()
  File "/home/archer/Adventure/main.py", line 152, in run
    self.active_scene = self.active_scene.next_scene()
  File "/home/archer/Adventure/main.py", line 44, in next_scene
    return PlayScene()
  File "/home/archer/Adventure/main.py", line 76, in __init__
    player = Player(0, SCREEN_HEIGHT - BLOCK_SIZE*3 - Player.HEIGHT + Player.BOTTOM_SPACE)
  File "/home/archer/Adventure/player.py", line 44, in __init__
    self.sprites.append(pygame.image.load(os.path.join('Assets\Player', 'Idle Sword/Idle Sword 01.png')))
FileNotFoundError: No file 'Assets\Player/Idle Sword/Idle Sword 01.png' found in working directory '/home/archer/Adventure'.
```

**Comment by SuperArcherG** [comment]
Fixed in https://github.com/Pandora241202/Adventure/pull/5
